version: '3.7'
services:
  apocalypse-api:
    build: .
    restart: always
    ports:
      - "8080:8080"
    container_name: apocalypse-api
    depends_on:
      - mongo-db
  mongo-db:
    image: mongo
    ports:
      - "27017:27017"
    container_name: mongo-db
    volumes:
      - ./db/:/data/db